### PR TITLE
update the change with the new way to get the ip

### PR DESCRIPTION
**Pull request by espoirMur**
I am new to this tablet, I got mine but I found that the tablet IP is now not static anymore, it keeps changing, so I added the steps to get it.

### CODE REVIEW

**Comment by ludovico** [comment]
Do you mean when you connect over WiFi? The `10.11.99.1` ip only works when you connect over USB 🙂

**Comment by dstango** [comment]
I find it useful to assign a fixed ip to the remarkable in my router's configuration :-)

**Comment by espoirMur** [comment]
> Do you mean when you connect over WiFi? The `10.11.99.1` ip only works when you connect over USB 🙂

When I connected mine I found that it was not using that ip address, it was saying a list of available IP addresses. 

And it kept assigning to the tab a random IP each time I connect..

**Comment by Eeems** [comment]
> When I connected mine I found that it was not using that ip address, it was saying a list of available IP addresses.
> 
> And it kept assigning to the tab a random IP each time I connect..

Is `10.11.99.1` one of them? Likely the other IP that's changing is for the wifi connection.

**Comment by espoirMur** [comment]
IMG_2152 copy
@Eeems looks for example what I have now, it is clear that the `10.11.99.1` is not one of them ....

**Comment by Eeems** [comment]
That's your wifi address. You need to plug in the USB to your computer and the device. If you have done so and the 10.11.99.1 address doesn't show up, either your computer is missing required software to negotiate the address, something is wrong with your cable, or something is wrong with your device.

**Comment by espoirMur** [comment]
> That's your wifi address. You need to plug in the USB to your computer and the device. If you have done so and the 10.11.99.1 address doesn't show up, either your computer is missing the required software to negotiate the address, something is wrong with your cable, or something is wrong with your device.

I got that when I connected my device to my mac via usb

**Comment by ddvk** [comment]
the ip of the tablet over USB is always the same because it is hard coded (the tablet runs a dhcp server and gives the host a dynamic ip). 
your usb connection is not working correctly, you would see 2 ip addess in the settings (the 10.11.99.1 which is hardcoded and the one your wifi router gave you)

**Comment by espoirMur** [comment]
Okay, @ddvk !!! 

You may be right, let me try it on another machine and see how it will behave...

**Comment by ddvk** [comment]
I guess we can close this :>

**Pull request closed without merging**
